# -*- mode: ruby -*-
# vi: set ft=ruby :

LOGIN       = ENV.fetch("LOGIN", "ibenmain")
VM_HOSTNAME = "#{LOGIN}S"
VM_IP       = "192.168.56.110"
BOX_NAME    = ENV.fetch("BOX_NAME", "bento/ubuntu-24.04")
VM_CPUS     = 1
VM_MEMORY   = 1024

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.boot_timeout     = 600
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define VM_HOSTNAME do |vm|
    vm.vm.box      = BOX_NAME
    vm.vm.hostname = VM_HOSTNAME

    vm.vm.network "private_network", ip: VM_IP

    vm.vm.provider "vmware_desktop" do |vf|
      vf.vmx["displayname"] = VM_HOSTNAME
      vf.cpus   = VM_CPUS
      vf.memory = VM_MEMORY
    end

    vm.vm.provision "file",  source: "configs", destination: "/tmp/k8s-configs"
    vm.vm.provision "shell", path: "scripts/common.sh"
    vm.vm.provision "shell", path: "scripts/k3s_server.sh"
  end
end
