LOGIN = ENV.fetch("LOGIN", "mqaos")
MASTER_HOSTNAME = "#{LOGIN}S"
WORKER_HOSTNAME = "#{LOGIN}SW"
MASTER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
BOX_NAME = ENV.fetch("BOX_NAME", "bento/ubuntu-24.04")
VM_CPUS   = 1
VM_MEMORY = 1024



Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.define MASTER_HOSTNAME do |master|
    master.vm.box = BOX_NAME
    master.vm.hostname = MASTER_HOSTNAME
    master.vm.network "private_network", ip: MASTER_IP
    master.vm.provider "vmware_desktop" do |vb|
      vb.cpus   = VM_CPUS
      vb.memory = VM_MEMORY
    end
    master.vm.provision "shell", path: "scripts/common.sh"
    master.vm.provision "shell", path: "scripts/master.sh"
  end
  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.box = BOX_NAME
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider "vmware_desktop" do |vb|
      vb.cpus   = VM_CPUS
      vb.memory = VM_MEMORY
    end
    worker.vm.provision "shell", path: "scripts/common.sh"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
